version: '2'
services:
  database_mysql:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: prometheus_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./DataStorage/database.sql:/docker-entrypoint-initdb.d/database.sql
      - db_data:/var/lib/mysql
volumes:
  db_data:

            
            
            