# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sla.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsla.proto\x12\x03sla\"<\n\x0bMetricValue\x12\x13\n\x0bmetric_name\x18\x01 \x01(\t\x12\x0b\n\x03min\x18\x02 \x01(\x05\x12\x0b\n\x03max\x18\x03 \x01(\x05\"D\n\nSlaRequest\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04hour\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x07\n\x05_nameB\x07\n\x05_hour\"\x17\n\x08SlaReply\x12\x0b\n\x03msg\x18\x01 \x01(\t\"I\n\tViolation\x12\x13\n\x0bmetric_name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x10\n\x03num\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\x06\n\x04_num2\xd8\x01\n\nSlaService\x12+\n\x06SetSla\x12\x10.sla.MetricValue\x1a\r.sla.SlaReply\"\x00\x12-\n\tSlaStatus\x12\x0f.sla.SlaRequest\x1a\r.sla.SlaReply\"\x00\x12\x33\n\x0cGetViolation\x12\x0f.sla.SlaRequest\x1a\x0e.sla.Violation\"\x00\x30\x01\x12\x39\n\x12GetFutureViolation\x12\x0f.sla.SlaRequest\x1a\x0e.sla.Violation\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sla_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METRICVALUE._serialized_start=18
  _METRICVALUE._serialized_end=78
  _SLAREQUEST._serialized_start=80
  _SLAREQUEST._serialized_end=148
  _SLAREPLY._serialized_start=150
  _SLAREPLY._serialized_end=173
  _VIOLATION._serialized_start=175
  _VIOLATION._serialized_end=248
  _SLASERVICE._serialized_start=251
  _SLASERVICE._serialized_end=467
# @@protoc_insertion_point(module_scope)
